# 예제 6.7 cv2.filter2D()와 cv2.sepFilter2D()에 의한 에지 검출
### <span style='background-color:#fff5b1'>cv2.filter2D(src, ddepth, kernel, anchor, borderType)</span>
**kernel** 1-채널 실수 배열로 src의 모든 채널에 동일하게 적용된다 \
**anchor** 커널의 중심점(kernel 내의 위치)
### <span style='background-color:#fff5b1'>cv2.sepFilter2D(src, ddepth, kernelX, kernelY, anchor, borderType)</span>
분리 가능한 선형 필터 kernelX, kernelY 적용하기

src의 각행에 커널 kernelX 적용한 결과의 각 열에 커널 kernelY를 적용하여 필터링한다

In [1]:
import cv2
import numpy as np

src = np.zeros(shape = (512, 512), dtype = np.uint8) + 255
cv2.rectangle(src, (100,100), (400,400), 0, 2)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

### <span style='background-color:#fff5b1'>cv2.getDerivKernels(dx, dy, ksize)</span>
미분 선형 필터 생성

In [2]:
kx, ky = cv2.getDerivKernels(1, 0, ksize = 3)
sobelX = ky.dot(kx.T)
print(kx)
print(ky)
print(sobelX)

[[-1.]
 [ 0.]
 [ 1.]]
[[1.]
 [2.]
 [1.]]
[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]


In [3]:
gx = cv2.filter2D(src, cv2.CV_32F, sobelX)

kx, ky = cv2.getDerivKernels(0, 1, ksize = 3)
sobelY = ky.dot(kx.T)
gy = cv2.filter2D(src, cv2.CV_32F, sobelY)

In [4]:
mag = cv2.magnitude(gx, gy)
ret, edge = cv2.threshold(mag, 100, 255, cv2.THRESH_BINARY)

cv2.imshow('edge', edge)
cv2.waitKey()
cv2.destroyAllWindows()