# 예제 4.6 ROI에 의한 불록 평균 영상

In [1]:
import cv2
import numpy as np

In [2]:
src = cv2.imread('../sample/why.jpeg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype = src.dtype)
print(src, src.shape)
print(dst, src.shape)

[[255 247 250 ... 248 248 248]
 [243 219 222 ... 215 215 215]
 [243 219 222 ... 215 215 215]
 ...
 [255 255 255 ... 220 219 219]
 [255 255 255 ... 215 215 214]
 [255 255 255 ... 251 251 250]] (199, 253)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] (199, 253)


In [3]:
N = 20 # 평균 낼 크기
height, width = src.shape
height, width

(199, 253)

In [4]:
h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        y = i * h
        x = j * w
        roi = src[y : y+h, x : x+h]
        dst[y : y+h, x : x+h] = cv2.mean(roi)[0]

In [5]:
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

![dst_screenshot_04 01 2023](https://user-images.githubusercontent.com/84698896/210504469-e03fcca6-e292-46a2-98b1-fc1604117544.png)