# 예제 4.12 채널 병합

In [1]:
import cv2

src = cv2.imread('../sample/why.jpeg')

In [2]:
b, g, r = cv2.split(src)
b, g, r

(array([[255, 254, 255, ..., 255, 255, 255],
        [252, 226, 231, ..., 231, 229, 231],
        [254, 228, 233, ..., 233, 231, 233],
        ...,
        [255, 255, 255, ..., 239, 238, 237],
        [255, 255, 255, ..., 231, 231, 228],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 247, 250, ..., 247, 247, 247],
        [243, 219, 222, ..., 213, 214, 213],
        [242, 219, 221, ..., 213, 213, 213],
        ...,
        [255, 255, 255, ..., 218, 217, 217],
        [255, 255, 255, ..., 213, 213, 213],
        [255, 255, 255, ..., 250, 250, 249]], dtype=uint8),
 array([[252, 244, 247, ..., 245, 245, 245],
        [240, 216, 219, ..., 212, 212, 212],
        [240, 216, 219, ..., 212, 212, 212],
        ...,
        [255, 255, 255, ..., 217, 216, 216],
        [255, 255, 255, ..., 212, 212, 211],
        [255, 255, 255, ..., 248, 248, 247]], dtype=uint8))

In [3]:
dst = cv2.merge([b, g, r])
type(dst)

numpy.ndarray

In [4]:
dst.shape

(199, 253, 3)

In [5]:
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()