# 예제 4.19 반전 영상

In [7]:
import cv2
import numpy as np

src1 = cv2.imread('../sample/why.jpeg', cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape = (199, 253), dtype = np.uint8) + 255

In [8]:
print(src1)
print(src2)

[[255 247 250 ... 248 248 248]
 [243 219 222 ... 215 215 215]
 [243 219 222 ... 215 215 215]
 ...
 [255 255 255 ... 220 219 219]
 [255 255 255 ... 215 215 214]
 [255 255 255 ... 251 251 250]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [9]:
dst1 = 255 - src1
dst1

array([[ 0,  8,  5, ...,  7,  7,  7],
       [12, 36, 33, ..., 40, 40, 40],
       [12, 36, 33, ..., 40, 40, 40],
       ...,
       [ 0,  0,  0, ..., 35, 36, 36],
       [ 0,  0,  0, ..., 40, 40, 41],
       [ 0,  0,  0, ...,  4,  4,  5]], dtype=uint8)

In [10]:
dst2 = cv2.subtract(src2, src1)
dst2

array([[ 0,  8,  5, ...,  7,  7,  7],
       [12, 36, 33, ..., 40, 40, 40],
       [12, 36, 33, ..., 40, 40, 40],
       ...,
       [ 0,  0,  0, ..., 35, 36, 36],
       [ 0,  0,  0, ..., 40, 40, 41],
       [ 0,  0,  0, ...,  4,  4,  5]], dtype=uint8)

In [11]:
dst3 = cv2.compare(dst1, dst2, cv2.CMP_NE)
dst3

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [13]:
n = cv2.countNonZero(dst3)
n

0

In [14]:
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()