# 예제 4.21 cv2.randu()에 2차원 균등 분포 난수 좌표

In [1]:
import cv2
import numpy as np
import time

In [6]:
dst = np.full((512, 512, 3), (255, 255, 255), dtype = np.uint8) # (255, 255, 3)을 512*512에 채운다
nPoints = 100
dst

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [8]:
pts = np.zeros((1, nPoints, 2), dtype = np.uint16)
pts

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        

In [9]:
pts.shape

(1, 100, 2)

### <span style='background-color:#fff5b1'>cv2.setRNGSeed(int(time.time())</span>
난수 생성 초기화

In [11]:
cv2.setRNGSeed(int(time.time()))

In [12]:
cv2.randu(pts, (0,0), (512,512))

array([[[100,  17],
        [241, 281],
        [354, 398],
        [440, 236],
        [ 81, 508],
        [ 67, 198],
        [409, 480],
        [216, 428],
        [  9, 468],
        [224, 336],
        [491, 236],
        [164,  24],
        [265, 510],
        [153, 374],
        [262, 350],
        [124, 271],
        [304,  95],
        [448, 134],
        [ 13, 327],
        [398, 208],
        [506, 235],
        [247,  19],
        [ 83,  31],
        [319, 233],
        [397, 242],
        [ 63, 131],
        [168, 422],
        [203, 121],
        [421, 229],
        [113, 103],
        [ 78, 169],
        [ 56, 462],
        [220, 365],
        [452,  19],
        [239, 171],
        [312, 290],
        [510, 127],
        [268, 428],
        [359, 176],
        [162, 406],
        [164, 385],
        [376,  60],
        [170, 350],
        [312, 449],
        [315, 432],
        [322,   9],
        [349, 356],
        [261, 468],
        [181, 494],
        [ 21, 351],


In [14]:
for k in range(nPoints):
    x, y = pts[0, k][:]
    cv2.circle(dst, (x,y), radius = 5, color = (0,0,255), thickness = -1)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()