# 예제 4.23 cv2.Mahalanobis()에 의한 통계적 거리 계산

In [1]:
import cv2
import numpy as np

In [2]:
X = np.array([[0,0,0,100,100,150,-100,-150],
              [0,50,-50,0,30,100,-20,-100]], dtype = np.float64)
X

array([[   0.,    0.,    0.,  100.,  100.,  150., -100., -150.],
       [   0.,   50.,  -50.,    0.,   30.,  100.,  -20., -100.]])

In [3]:
X = X.transpose()
X

array([[   0.,    0.],
       [   0.,   50.],
       [   0.,  -50.],
       [ 100.,    0.],
       [ 100.,   30.],
       [ 150.,  100.],
       [-100.,  -20.],
       [-150., -100.]])

In [4]:
cov, mean = cv2.calcCovarMatrix(X, mean = None, flags = cv2.COVAR_NORMAL + cv2.COVAR_ROWS)
cov, mean

(array([[73750. , 34875. ],
        [34875. , 26287.5]]),
 array([[12.5 ,  1.25]]))

In [5]:
ret, icov = cv2.invert(cov)
icov

array([[ 3.63872307e-05, -4.82740722e-05],
       [-4.82740722e-05,  1.02084955e-04]])

In [6]:
v1 = np.array([[0], [0]], dtype = np.float64)
v2 = np.array([[0], [5]], dtype = np.float64)

dist = cv2.Mahalanobis(v1, v2, icov)
dist

0.05051854992128457