# 예제 4.24 cv2.Mahalanobis() 통계적 거리 계산, 공분산 행렬의 고유값과 고유 벡터

In [1]:
import cv2
import numpy as np

In [2]:
X = np.array([[0,0,0,100,100,150,-100,-150],
              [0,50,-50,0,30,100,-20,-100]], dtype = np.float64)
X = X.transpose()
X

array([[   0.,    0.],
       [   0.,   50.],
       [   0.,  -50.],
       [ 100.,    0.],
       [ 100.,   30.],
       [ 150.,  100.],
       [-100.,  -20.],
       [-150., -100.]])

In [3]:
cov, mean = cv2.calcCovarMatrix(X, mean = None, flags = cv2.COVAR_NORMAL + cv2.COVAR_ROWS)
ret, icov = cv2.invert(cov)

In [7]:
dst = np.full((512,512,3), (255,255,255), dtype=np.uint8)
dst

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [8]:
rows, cols, channel = dst.shape
centerX = cols // 2
centerY = rows // 2

In [9]:
v2 = np.zeros((1,2), dtype=np.float64)
v2

array([[0., 0.]])

In [10]:
FLIP_Y = lambda y:rows -1 -y
FLIP_Y

<function __main__.<lambda>(y)>

In [ ]:
for y in range(rows):
    for x in range(cols):
        v2[0,0] = x-centerX
        v2[0,1] = FLIP_Y(y) - centerY
        dist = cv2.Mahalanobis(mean, v2, icov)
        if dist < 0.1:
            dst[y.x] = [50,50,50]
        elif dist < 0.3:
            dst[y,x] = [100,100,100]
        elif dist < 0.8:
            dst[y,x] = [200,200,200]
        else:
            dst[y,x] = [250,250,250]