# 예제 7.2 직선 검출: cv2.HoughLines()

In [1]:
import cv2
import numpy as np

### <span style='background-color:#fff5b1'>cv2.HoughLines(edges, rho, theta, threshold)</span>
1-채널 8비트 image에서 lines 검출하여 반환 \
**lines** 검출된 직선의 parameter가 저장된 배열 \
**rho** 원점으로부터의 거리 간격 \
**theta** x축과의 각도(라디안) \
**threshold** 직선을 검출하기 위한 어큐뮬레이터의 임계값

In [2]:
src = np.zeros(shape=(512,512), dtype = np.uint8) + 255
cv2.rectangle(src, (100,100), (400,400), 0, -1)
edges = cv2.Canny(src, 50, 100)
lines = cv2.HoughLines(edges, rho = 1, theta = np.pi / 180.0, threshold = 100)
print(lines.shape)
print(lines)

(4, 1, 2)
[[[400.          0.       ]]

 [[400.          1.5707964]]

 [[ 99.          0.       ]]

 [[ 99.          1.5707964]]]


In [3]:
for line in lines:
    rho, theta = line[0]
    c = np.cos(theta)
    s = np.sin(theta)
    x0 = c * rho
    y0 = s * rho
    x1 = int(x0 + 1000 * (-s))
    y1 = int(y0 + 1000 * (c))
    x2 = int(x0 - 1000 * (-s))
    y2 = int(y0 - 1000 * (c))
    cv2.line(src, (x1, y1), (x2, y2), (0,0,255), 2)

In [4]:
cv2.imshow('edges', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

# 예제 7.3 선분 검출: cv2.HoughLinesP()
### <span style='background-color:#fff5b1'>cv2.HoughLinesP(edges, rho, theta, threshold)</span>
probabilistic Hough 변환을 이용하여 양 긑점이 있는 선분을 lines에 검출하여 반환 \
**lines** 선분의 양 끝점 (x1, y1, x2, y2)을 저장하는 배열 \
**rho** 원점으로부터의 거리 간격 \
**theta**  x축과의 각도(라디안) \
**threshold** 직선을 검출하기 위한 어큐뮬레이터의 임계값 \
**minLineLength** 검출할 최소 직선의 길이 \
**maxLineGap** 직선 위의 edge들의 최대 허용 간격

In [5]:
src = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
cv2.rectangle(src, (100,100), (400,400), 0, -1)

edges = cv2.Canny(src, 50, 100)
lines = cv2.HoughLinesP(edges, rho = 1, theta = np.pi / 180.0, threshold = 100)
print(lines.shape)
print(lines)

(4, 1, 4)
[[[100 400 400 400]]

 [[101  99 399  99]]

 [[ 99 399  99 101]]

 [[400 399 400 100]]]


In [6]:
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)

In [7]:
cv2.imshow('edges', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

# 예제 7.4 원 검출: cv2.HoughCircles()
### <span style='background-color:#fff5b1'>cv2.HoughCircles(image, method, dp, minDist, param2)</span>
1-채널 8비트 grayscale 영상 image에서 원을 찾아 원의 매개변수 (cx, cy, r)를 저장한 배열 circles를 반환 \
**method** cv2.HOUGH_GRADIENT 방법만 구현되어 있음 \
**dp** 어큐뮬레이터 간격에서 영상 간격으로의 역 비율 \
**minDist** 검출된 원의 중심 사이의 최소 거리 -> 너무 작으면 많은 원이 검출되고 너무 크면 검출하지 못하는 원이 있을 수 있음 \
**param1** Canny edge 검출의 높은 임계값 threshold2(threshold1은 param1/2) \
**param2** 어큐뮬레이터의 임계값 \
**minRadius** 원의 최소 반지름 \
**maxRadius** 원의 최대 반지름

In [8]:
src1 = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
cv2.circle(src1, (200,200), 80, 0, -1)
cv2.circle(src1, (80,80), 60, 0, -1)
cv2.circle(src1, (350,350), 80, 0, -1)
cv2.circle(src1, (170, 480), 20, 0, -1)
cv2.circle(src1, (460, 100), 10, 0, -1)
gray1 = cv2.cvtColor(src1, cv2.COLOR_BGR2GRAY)

circles1 = cv2.HoughCircles(gray1, method = cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15)
circles1 = np.int32(circles1)
print(circles1.shape)
print(circles1)

(1, 5, 3)
[[[348 349  79]
  [198 200  80]
  [ 78  80  60]
  [171 480  21]
  [460 100   9]]]


In [9]:
for circle in circles1[0,:]:
    cx, cy, r = circle
    cv2.circle(src1, (cx, cy), r, (0,0,255), 2)

In [10]:
cv2.imshow('circles1', src1)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
src2 = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
cv2.circle(src2, (200,200), 80, 0, -1)
cv2.circle(src2, (80,80), 60, 0, -1)
cv2.circle(src2, (350,350), 80, 0, -1)
cv2.circle(src2, (170, 480), 20, 0, -1)
cv2.circle(src2, (460, 100), 10, 0, -1)
gray2 = cv2.cvtColor(src2, cv2.COLOR_BGR2GRAY)

circles2 = cv2.HoughCircles(gray2, method = cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15, minRadius=30, maxRadius=100)
circles2 = np.int32(circles2)
print(circles2.shape)
print(circles2)

(1, 3, 3)
[[[198 200  80]
  [348 350  80]
  [ 78  80  60]]]


In [12]:
for circle in circles2[0,:]:
    cx, cy, r = circle
    cv2.circle(src2, (cx, cy), r, (0,0,255), 2)

In [13]:
cv2.imshow('src2', src2)
cv2.waitKey()
cv2.destroyAllWindows()