In [1]:
import cv2
import numpy as np

# 예제 7.6 윤곽선 검출 및 그리기 1: mode = cv2.RETR_EXTERNAL
### <span style='background-color:#fff5b1'>cv2.findContours(image, mode, method)
1-채널 8비트 영상 image에서 윤곽선을 검출하여 리스트 형태로 반환, 윤곽선 계층 구조에 관한 배열 hierarchy 반환 \
**mode** 윤곽선의 검색 모드(가장 외곽 RETR_EXTERNAL, 모든 윤곽선 RETR_LIST, 계층 구조의 모든 윤곽선 RETR_CCOMP, 계층적 트리 형태의 모든 윤곽선 RETR_TREE) \
**method** 윤곽선의 근사 방법

In [2]:
src = np.zeros(shape = (512,512,3), dtype = np.uint8)
cv2.rectangle(src, (50,100), (450,400), (255,255,255), -1)
cv2.rectangle(src, (100,150), (400,350), (0,0,0), -1)
cv2.rectangle(src, (200,200), (300,300), (255,255,255), -1)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

In [3]:
mode = cv2.RETR_EXTERNAL
method = cv2.CHAIN_APPROX_SIMPLE
contours, hierarchy = cv2.findContours(gray, mode, method)
print(type(contours), type(contours[0]), len(contours), contours[0].shape)
print(contours[0])

<class 'tuple'> <class 'numpy.ndarray'> 1 (4, 1, 2)
[[[ 50 100]]

 [[ 50 400]]

 [[450 400]]

 [[450 100]]]


In [4]:
cv2.drawContours(src, contours, -1, (255,0,0), 3)

for pt in contours[0][:]:
    cv2.circle(src, (pt[0][0], pt[0][1]), 5, (0,0,255), -1)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

# 예제 7.8 윤곽선 검출 및 그리기 2: mode = cv2.RETR_LIST
모든 윤곽선 검출

In [5]:
src = np.zeros(shape = (512,512,3), dtype = np.uint8)
cv2.rectangle(src, (50, 100), (450,400), (255,255,255), -1)
cv2.rectangle(src, (100,150), (400,350), (0,0,0), -1)
cv2.rectangle(src, (200,200), (300,300), (255,255,255), -1)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

In [6]:
mode = cv2.RETR_LIST
method = cv2.CHAIN_APPROX_SIMPLE
contours, hierarchy = cv2.findContours(gray, mode, method)
print(len(contours), contours[0].shape)
print(contours)

3 (4, 1, 2)
(array([[[200, 200]],

       [[200, 300]],

       [[300, 300]],

       [[300, 200]]], dtype=int32), array([[[ 99, 150]],

       [[100, 149]],

       [[400, 149]],

       [[401, 150]],

       [[401, 350]],

       [[400, 351]],

       [[100, 351]],

       [[ 99, 350]]], dtype=int32), array([[[ 50, 100]],

       [[ 50, 400]],

       [[450, 400]],

       [[450, 100]]], dtype=int32))


In [7]:
for cnt in contours:
    cv2.drawContours(src, [cnt], 0, (255,0,0), 3)
    for pt in cnt:
        cv2.circle(src, (pt[0][0], pt[0][1]), 5, (0,0,255), -1)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()