# 예제 7.14 cv2.kmeans() 컬러 클러스터링 영역 검출
### <span style='background-color:#fff5b1'>cv2.kmeans(data, K, bestLabels, criteria, attempts, flags)</span>
**data** 클러스터링을 위한 데이터 \
**K** 클러스터 개수 \
**bestLabels** 각 샘플의 클러스터 번호를 labels에 저장 \
**criteria** 종료 조건(반복 회수와 오차 범위) \
**attempts** 알고리즘을 시도하는 횟수 -> 최적의 레이블링 결과를 bestLabels에 저장하여 반환 \
클러스터의 중심 centers 반환 \
**flag** K개의 클러스터 중심을 초기화하는 방법

In [1]:
import cv2
import numpy as np

src = cv2.imread('../sample/hand.jpg')
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

In [2]:
data = src.reshape((-1,3)).astype(np.float32)
data

array([[255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.],
       ...,
       [255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.]], dtype=float32)

In [3]:
K = 2
term_crit = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
ret, labels, centers = cv2.kmeans(data, K, None, term_crit, 5, cv2.KMEANS_RANDOM_CENTERS)
centers.shape, labels.shape, ret

((2, 3), (220000, 1), 407756994.4463509)

In [4]:
print(labels)
print(labels.flatten())

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1 1 1 ... 1 1 1]


In [5]:
centers = np.uint8(centers)
res = centers[labels.flatten()]
dst = res.reshape(src.shape)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()