# 예제 3.1 직선 및 사각형 그리기

**numpy** numerical python: 벡터 및 행렬 연산을 위한 python library\
**np.array(list)** list를 ndarray type으로 변경\
**array.shape** (x, y, z) 축 순서대로 출력\
**array.dtype** dtype('int64) dtype('float64')

### <span style='background-color:#fff5b1'>numpy 연산</span>
\+ 덧셈, - 뺄셈, * element 곱셈, @ 내적

In [1]:
import cv2
import numpy as np

### <span style='background-color:#fff5b1'>np.zeros(shape = (w, x, y), dtype = np.uint8) + 255</span>
usigned int w * x * y 크기의 배열(ndarray)를 255(흰색)로 초기화

In [2]:
img = np.zeros(shape = (512,512,3), dtype = np.uint8) + 255 # unsigned int 512 * 512 * 3 모두 255로 초기화
print(img[0], img.shape)

[[255 255 255]
 [255 255 255]
 [255 255 255]
 ...
 [255 255 255]
 [255 255 255]
 [255 255 255]] (512, 512, 3)


### <span style='background-color:#fff5b1'>cv2.rectangle(img, point1, point2, color, thickness)</span>
img 위에 point1, point2로 정의되는 직사각형을 그리기\
**thickness == -1** 이면 color 색상으로 채운 사각형을 그린다
### <span style='background-color:#fff5b1'>cv2.line(img, pt1, pt2, color, thickness)</span>
pt1, pt2를 연결하는 직선 그리기

In [3]:
pt1 = 100, 100 # tuple
pt2 = 400, 400

cv2.rectangle(img, pt1, pt2, (0, 255, 0), 2)

cv2.line(img, (0, 0), (500, 0), (255, 0, 0), 5)
cv2.line(img, (0, 0), (0, 500), (0, 0, 255), 5)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

![image](https://user-images.githubusercontent.com/84698896/209605763-ef6958e4-26f7-4a85-ab62-db38b5e41d93.png)