# 예제 5.2 히스토그램 계산 1
### <span style='background-color:#fff5b1'>cv2.chlcHist(images, channels, mask, histSize, range) -> hist</span>
**images** 히스토그램을 계산할 영상 배열 \
**challens** 히스토그램을 계산할 채널 번호를 갖는 정수형 배열 \
**mask** images[i]와 같은 크기의 8비트 영상 \
**histSize** hist의 각 bin 크기에 대한 정수 배열 \
**range** 각 bin의 경계값 배열의 배열

In [1]:
import cv2
import numpy as np

src = np.array([[0,0,0,0],
                [1,1,3,5],
                [6,1,1,3],
                [4,3,1,7]
                ], dtype=np.uint8)
src

array([[0, 0, 0, 0],
       [1, 1, 3, 5],
       [6, 1, 1, 3],
       [4, 3, 1, 7]], dtype=uint8)

0과 1: 9개 \
2와 3: 3개 \
4와 5: 2개 \
6과 7: 2개

**images** 히스토그램을 계산할 영상 배열 [src] \
**challens** 히스토그램을 계산할 채널 번호를 갖는 정수형 배열 [0] \
**mask** images[i]와 같은 크기의 8비트 영상 None \
**histSize** hist의 각 bin 크기에 대한 정수 배열 -> 출력될 배열의 개수, 구간의 개수 len(hist1) \
**range** 각 bin의 경계값 배열의 배열 -> 0 이상 8 미만 -> 0부터 7까지의 개수만 센다

In [2]:
hist1 = cv2.calcHist(images=[src], channels=[0], mask=None, histSize=[4], ranges=[0,8])
hist1

array([[9.],
       [3.],
       [2.],
       [2.]], dtype=float32)

In [3]:
hist2 = cv2.calcHist(images=[src], channels=[0], mask=None, histSize=[4], ranges=[0,4])
hist2

array([[4.],
       [5.],
       [0.],
       [3.]], dtype=float32)