# 예제 5.8 Hue-채널의 히스토그램 역투영

In [19]:
import cv2
import numpy as np

In [20]:
src = cv2.imread('../sample/lena.png')
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
print(hsv)
h, s, v = cv2.split(hsv)
h, s, v

[[[  4 114 226]
  [  4 114 226]
  [  1 103 223]
  ...
  [  7 120 230]
  [  5 128 221]
  [  2 140 200]]

 [[  4 114 226]
  [  4 114 226]
  [  1 103 223]
  ...
  [  7 120 230]
  [  5 128 221]
  [  2 140 200]]

 [[  4 114 226]
  [  4 114 226]
  [  1 103 223]
  ...
  [  7 120 230]
  [  5 128 221]
  [  2 140 200]]

 ...

 [[161 200  84]
  [161 200  84]
  [166 180  92]
  ...
  [177 147 173]
  [178 154 172]
  [176 166 177]]

 [[163 187  82]
  [163 187  82]
  [166 170  96]
  ...
  [178 155 179]
  [177 155 181]
  [178 153 185]]

 [[163 187  82]
  [163 187  82]
  [166 170  96]
  ...
  [178 155 179]
  [177 155 181]
  [178 153 185]]]


(array([[  4,   4,   1, ...,   7,   5,   2],
        [  4,   4,   1, ...,   7,   5,   2],
        [  4,   4,   1, ...,   7,   5,   2],
        ...,
        [161, 161, 166, ..., 177, 178, 176],
        [163, 163, 166, ..., 178, 177, 178],
        [163, 163, 166, ..., 178, 177, 178]], dtype=uint8),
 array([[114, 114, 103, ..., 120, 128, 140],
        [114, 114, 103, ..., 120, 128, 140],
        [114, 114, 103, ..., 120, 128, 140],
        ...,
        [200, 200, 180, ..., 147, 154, 166],
        [187, 187, 170, ..., 155, 155, 153],
        [187, 187, 170, ..., 155, 155, 153]], dtype=uint8),
 array([[226, 226, 223, ..., 230, 221, 200],
        [226, 226, 223, ..., 230, 221, 200],
        [226, 226, 223, ..., 230, 221, 200],
        ...,
        [ 84,  84,  92, ..., 173, 172, 177],
        [ 82,  82,  96, ..., 179, 181, 185],
        [ 82,  82,  96, ..., 179, 181, 185]], dtype=uint8))

In [21]:
roi = cv2.selectROI(src)
print(roi)
roi_h = h[roi[1]:roi[1] + roi[3], roi[0]:roi[0] + roi[2]]

Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
(234, 221, 103, 165)


In [22]:
hist = cv2.calcHist([roi_h], [0], None, [64], [0,256])
backP = cv2.calcBackProject([h.astype(np.float32)], [0], hist, [0,256], scale=1.0)

In [23]:
hist = cv2.sort(hist, cv2.SORT_EVERY_COLUMN+cv2.SORT_DESCENDING)
k = 1
T = hist[k][0] -1
T

5561.0

In [24]:
ret, dst = cv2.threshold(backP, T, 255, cv2.THRESH_BINARY)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()